### ISSUE TITLE
when will you release the code 

### ISSUE THREAD

**Issue by Daniellli** [yyliu01/IT2#1]
same as the title

**Comment by yyliu01** [comment]
Hi @Daniellli 

Thank you very much for your interest! I have read your paper on point cloud anomaly detection, which is an interesting work and provides me with many insights.

For this project, I am currently in a very busy period as I am preparing to move to a new position for my postdoctoral research. After formatting the code and double-checking its performance, I promise everything will be released within the next two months, before the ECCV conference.

Cheers,
Yuyuan

**Comment by yyliu01** [comment]
Hi @Daniellli 

I've uploaded the code, some reproduced checkpoints, and the W&B visualisation, which you can find here: [W&B Visualisation](https://wandb.ai/pyedog1976/IT2?nw=nwuserpyedog1976). Full details about deployments and environments will be released soon.

Thanks for your interest.

Cheers,
Yuyuan
