### ISSUE TITLE
Question about ensembling of labels

### ISSUE THREAD

**Issue by binyang97** [yyliu01/IT2#2]
Hi, 

thank you for the great work and release of source code. I saw you demonstrated some results with ensembled labels from two modalities in the supplementary. What is the ensembling method you used to produce that results?

Best,
Bin

**Comment by yyliu01** [comment]
Please refer to [these lines](https://github.com/yyliu01/IT2/blob/e3b83f7dd7c5178e43f272e6f0453872a3e3dae1/nuscenes.code.ItTakesTwo.gmm/modality/network.py#L46C1-L65C32).
