### ISSUE TITLE
Contrastive loss

### ISSUE THREAD

**Issue by WAAutomation** [yyliu01/IT2#3]
Thanks for your outstanding work.
![image](https://github.com/user-attachments/assets/25a6b44a-cbf7-4510-a5ff-090a8922bcab)
This loss is similar to InfoNCE loss, I wander why this loss do not have the '-log'
![image](https://github.com/user-attachments/assets/70357902-4560-45c9-8d1e-362d29d16dac)

**Comment by yyliu01** [comment]
Hi @WAAutomation 

Yes, it should be a typo in the paper and I'll update it soon in the arxiv. 
Please note that our implementation contains neglog in [here](https://github.com/yyliu01/IT2/blob/e3b83f7dd7c5178e43f272e6f0453872a3e3dae1/nuscenes.code.ItTakesTwo.gmm/utils/losses/batch_prototype_info_nce_loss.py#L95). Thanks for bring it up.

Cheers,
Yuyuan

**Comment by yyliu01** [comment]
Sorry for the delay, the fixed version has been updated.
